/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.CampaignA;
import io.github.erkoristhein.mailchimp.marketing.model.CampaignB;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ABSplitStats
 */
class ABSplitStatsTest {
    private final ABSplitStats model = new ABSplitStats();

    /**
     * Model tests for ABSplitStats
     */
    @Test
    void testABSplitStats() {
        // TODO: test ABSplitStats
    }

    /**
     * Test the property 'a'
     */
    @Test
    void aTest() {
        // TODO: test a
    }

    /**
     * Test the property 'b'
     */
    @Test
    void bTest() {
        // TODO: test b
    }

}
