/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CampaignFeedback
 */
class CampaignFeedbackTest {
    private final CampaignFeedback model = new CampaignFeedback();

    /**
     * Model tests for CampaignFeedback
     */
    @Test
    void testCampaignFeedback() {
        // TODO: test CampaignFeedback
    }

    /**
     * Test the property 'feedbackId'
     */
    @Test
    void feedbackIdTest() {
        // TODO: test feedbackId
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'blockId'
     */
    @Test
    void blockIdTest() {
        // TODO: test blockId
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'isComplete'
     */
    @Test
    void isCompleteTest() {
        // TODO: test isComplete
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'source'
     */
    @Test
    void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'campaignId'
     */
    @Test
    void campaignIdTest() {
        // TODO: test campaignId
    }

    /**
     * Test the property 'links'
     */
    @Test
    void linksTest() {
        // TODO: test links
    }

}
