/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CampaignFeedback1
 */
class CampaignFeedback1Test {
    private final CampaignFeedback1 model = new CampaignFeedback1();

    /**
     * Model tests for CampaignFeedback1
     */
    @Test
    void testCampaignFeedback1() {
        // TODO: test CampaignFeedback1
    }

    /**
     * Test the property 'blockId'
     */
    @Test
    void blockIdTest() {
        // TODO: test blockId
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'isComplete'
     */
    @Test
    void isCompleteTest() {
        // TODO: test isComplete
    }

}
