/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CampaignReportSummary
 */
class CampaignReportSummaryTest {
    private final CampaignReportSummary model = new CampaignReportSummary();

    /**
     * Model tests for CampaignReportSummary
     */
    @Test
    void testCampaignReportSummary() {
        // TODO: test CampaignReportSummary
    }

    /**
     * Test the property 'opens'
     */
    @Test
    void opensTest() {
        // TODO: test opens
    }

    /**
     * Test the property 'uniqueOpens'
     */
    @Test
    void uniqueOpensTest() {
        // TODO: test uniqueOpens
    }

    /**
     * Test the property 'openRate'
     */
    @Test
    void openRateTest() {
        // TODO: test openRate
    }

    /**
     * Test the property 'clicks'
     */
    @Test
    void clicksTest() {
        // TODO: test clicks
    }

    /**
     * Test the property 'subscriberClicks'
     */
    @Test
    void subscriberClicksTest() {
        // TODO: test subscriberClicks
    }

    /**
     * Test the property 'clickRate'
     */
    @Test
    void clickRateTest() {
        // TODO: test clickRate
    }

}
