/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChimpChatter
 */
class ChimpChatterTest {
    private final ChimpChatter model = new ChimpChatter();

    /**
     * Model tests for ChimpChatter
     */
    @Test
    void testChimpChatter() {
        // TODO: test ChimpChatter
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'url'
     */
    @Test
    void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'listId'
     */
    @Test
    void listIdTest() {
        // TODO: test listId
    }

    /**
     * Test the property 'campaignId'
     */
    @Test
    void campaignIdTest() {
        // TODO: test campaignId
    }

}
