/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Clicks
 */
class ClicksTest {
    private final Clicks model = new Clicks();

    /**
     * Model tests for Clicks
     */
    @Test
    void testClicks() {
        // TODO: test Clicks
    }

    /**
     * Test the property 'clicksTotal'
     */
    @Test
    void clicksTotalTest() {
        // TODO: test clicksTotal
    }

    /**
     * Test the property 'uniqueClicks'
     */
    @Test
    void uniqueClicksTest() {
        // TODO: test uniqueClicks
    }

    /**
     * Test the property 'uniqueSubscriberClicks'
     */
    @Test
    void uniqueSubscriberClicksTest() {
        // TODO: test uniqueSubscriberClicks
    }

    /**
     * Test the property 'clickRate'
     */
    @Test
    void clickRateTest() {
        // TODO: test clickRate
    }

    /**
     * Test the property 'lastClick'
     */
    @Test
    void lastClickTest() {
        // TODO: test lastClick
    }

}
