/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.EmailChannelDetails;
import io.github.erkoristhein.mailchimp.marketing.model.SMSChannelDetails;
import io.github.erkoristhein.mailchimp.marketing.model.Source;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContactsInner
 */
class ContactsInnerTest {
    private final ContactsInner model = new ContactsInner();

    /**
     * Model tests for ContactsInner
     */
    @Test
    void testContactsInner() {
        // TODO: test ContactsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'audienceId'
     */
    @Test
    void audienceIdTest() {
        // TODO: test audienceId
    }

    /**
     * Test the property 'language'
     */
    @Test
    void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'emailChannel'
     */
    @Test
    void emailChannelTest() {
        // TODO: test emailChannel
    }

    /**
     * Test the property 'smsChannel'
     */
    @Test
    void smsChannelTest() {
        // TODO: test smsChannel
    }

    /**
     * Test the property 'mergeFields'
     */
    @Test
    void mergeFieldsTest() {
        // TODO: test mergeFields
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'source'
     */
    @Test
    void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'lastUpdatedAt'
     */
    @Test
    void lastUpdatedAtTest() {
        // TODO: test lastUpdatedAt
    }

}
