/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DailyListActivity
 */
class DailyListActivityTest {
    private final DailyListActivity model = new DailyListActivity();

    /**
     * Model tests for DailyListActivity
     */
    @Test
    void testDailyListActivity() {
        // TODO: test DailyListActivity
    }

    /**
     * Test the property 'day'
     */
    @Test
    void dayTest() {
        // TODO: test day
    }

    /**
     * Test the property 'emailsSent'
     */
    @Test
    void emailsSentTest() {
        // TODO: test emailsSent
    }

    /**
     * Test the property 'uniqueOpens'
     */
    @Test
    void uniqueOpensTest() {
        // TODO: test uniqueOpens
    }

    /**
     * Test the property 'recipientClicks'
     */
    @Test
    void recipientClicksTest() {
        // TODO: test recipientClicks
    }

    /**
     * Test the property 'hardBounce'
     */
    @Test
    void hardBounceTest() {
        // TODO: test hardBounce
    }

    /**
     * Test the property 'softBounce'
     */
    @Test
    void softBounceTest() {
        // TODO: test softBounce
    }

    /**
     * Test the property 'subs'
     */
    @Test
    void subsTest() {
        // TODO: test subs
    }

    /**
     * Test the property 'unsubs'
     */
    @Test
    void unsubsTest() {
        // TODO: test unsubs
    }

    /**
     * Test the property 'otherAdds'
     */
    @Test
    void otherAddsTest() {
        // TODO: test otherAdds
    }

    /**
     * Test the property 'otherRemoves'
     */
    @Test
    void otherRemovesTest() {
        // TODO: test otherRemoves
    }

    /**
     * Test the property 'links'
     */
    @Test
    void linksTest() {
        // TODO: test links
    }

}
