/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ECommerceProduct1;
import java.math.BigDecimal;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ECommerceOrderLineItem2
 */
class ECommerceOrderLineItem2Test {
    private final ECommerceOrderLineItem2 model = new ECommerceOrderLineItem2();

    /**
     * Model tests for ECommerceOrderLineItem2
     */
    @Test
    void testECommerceOrderLineItem2() {
        // TODO: test ECommerceOrderLineItem2
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'productId'
     */
    @Test
    void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'productVariantId'
     */
    @Test
    void productVariantIdTest() {
        // TODO: test productVariantId
    }

    /**
     * Test the property 'product'
     */
    @Test
    void productTest() {
        // TODO: test product
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'price'
     */
    @Test
    void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'discount'
     */
    @Test
    void discountTest() {
        // TODO: test discount
    }

}
