/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner;
import io.github.erkoristhein.mailchimp.marketing.model.GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecs
 */
class GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsTest {
    private final GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecs model = new GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecs();

    /**
     * Model tests for GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecs
     */
    @Test
    void testGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecs() {
        // TODO: test GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecs
    }

    /**
     * Test the property 'gender'
     */
    @Test
    void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'minAge'
     */
    @Test
    void minAgeTest() {
        // TODO: test minAge
    }

    /**
     * Test the property 'maxAge'
     */
    @Test
    void maxAgeTest() {
        // TODO: test maxAge
    }

    /**
     * Test the property 'locations'
     */
    @Test
    void locationsTest() {
        // TODO: test locations
    }

    /**
     * Test the property 'interests'
     */
    @Test
    void interestsTest() {
        // TODO: test interests
    }

}
