/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GroupA
 */
class GroupATest {
    private final GroupA model = new GroupA();

    /**
     * Model tests for GroupA
     */
    @Test
    void testGroupA() {
        // TODO: test GroupA
    }

    /**
     * Test the property 'totalClicksA'
     */
    @Test
    void totalClicksATest() {
        // TODO: test totalClicksA
    }

    /**
     * Test the property 'clickPercentageA'
     */
    @Test
    void clickPercentageATest() {
        // TODO: test clickPercentageA
    }

    /**
     * Test the property 'uniqueClicksA'
     */
    @Test
    void uniqueClicksATest() {
        // TODO: test uniqueClicksA
    }

    /**
     * Test the property 'uniqueClickPercentageA'
     */
    @Test
    void uniqueClickPercentageATest() {
        // TODO: test uniqueClickPercentageA
    }

}
