/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.81
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for MergeFieldOptions1
 */
public class MergeFieldOptions1Test {
    private final MergeFieldOptions1 model = new MergeFieldOptions1();

    /**
     * Model tests for MergeFieldOptions1
     */
    @Test
    public void testMergeFieldOptions1() {
        // TODO: test MergeFieldOptions1
    }

    /**
     * Test the property 'defaultCountry'
     */
    @Test
    public void defaultCountryTest() {
        // TODO: test defaultCountry
    }

    /**
     * Test the property 'phoneFormat'
     */
    @Test
    public void phoneFormatTest() {
        // TODO: test phoneFormat
    }

    /**
     * Test the property 'dateFormat'
     */
    @Test
    public void dateFormatTest() {
        // TODO: test dateFormat
    }

    /**
     * Test the property 'choices'
     */
    @Test
    public void choicesTest() {
        // TODO: test choices
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

}
