/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Opens
 */
class OpensTest {
    private final Opens model = new Opens();

    /**
     * Model tests for Opens
     */
    @Test
    void testOpens() {
        // TODO: test Opens
    }

    /**
     * Test the property 'opensTotal'
     */
    @Test
    void opensTotalTest() {
        // TODO: test opensTotal
    }

    /**
     * Test the property 'proxyExcludedOpens'
     */
    @Test
    void proxyExcludedOpensTest() {
        // TODO: test proxyExcludedOpens
    }

    /**
     * Test the property 'uniqueOpens'
     */
    @Test
    void uniqueOpensTest() {
        // TODO: test uniqueOpens
    }

    /**
     * Test the property 'proxyExcludedUniqueOpens'
     */
    @Test
    void proxyExcludedUniqueOpensTest() {
        // TODO: test proxyExcludedUniqueOpens
    }

    /**
     * Test the property 'openRate'
     */
    @Test
    void openRateTest() {
        // TODO: test openRate
    }

    /**
     * Test the property 'proxyExcludedOpenRate'
     */
    @Test
    void proxyExcludedOpenRateTest() {
        // TODO: test proxyExcludedOpenRate
    }

    /**
     * Test the property 'lastOpen'
     */
    @Test
    void lastOpenTest() {
        // TODO: test lastOpen
    }

}
