/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.SendingSchedule;
import java.net.URI;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RSSOptions
 */
class RSSOptionsTest {
    private final RSSOptions model = new RSSOptions();

    /**
     * Model tests for RSSOptions
     */
    @Test
    void testRSSOptions() {
        // TODO: test RSSOptions
    }

    /**
     * Test the property 'feedUrl'
     */
    @Test
    void feedUrlTest() {
        // TODO: test feedUrl
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'lastSent'
     */
    @Test
    void lastSentTest() {
        // TODO: test lastSent
    }

    /**
     * Test the property 'constrainRssImg'
     */
    @Test
    void constrainRssImgTest() {
        // TODO: test constrainRssImg
    }

}
