/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.EcommerceStats;
import java.math.BigDecimal;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubscriberStats1
 */
class SubscriberStats1Test {
    private final SubscriberStats1 model = new SubscriberStats1();

    /**
     * Model tests for SubscriberStats1
     */
    @Test
    void testSubscriberStats1() {
        // TODO: test SubscriberStats1
    }

    /**
     * Test the property 'avgOpenRate'
     */
    @Test
    void avgOpenRateTest() {
        // TODO: test avgOpenRate
    }

    /**
     * Test the property 'avgClickRate'
     */
    @Test
    void avgClickRateTest() {
        // TODO: test avgClickRate
    }

    /**
     * Test the property 'ecommerceData'
     */
    @Test
    void ecommerceDataTest() {
        // TODO: test ecommerceData
    }

}
