/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.81
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for SubscriberInAutomationQueue2
 */
public class SubscriberInAutomationQueue2Test {
    private final SubscriberInAutomationQueue2 model = new SubscriberInAutomationQueue2();

    /**
     * Model tests for SubscriberInAutomationQueue2
     */
    @Test
    public void testSubscriberInAutomationQueue2() {
        // TODO: test SubscriberInAutomationQueue2
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'workflowId'
     */
    @Test
    public void workflowIdTest() {
        // TODO: test workflowId
    }

    /**
     * Test the property 'emailId'
     */
    @Test
    public void emailIdTest() {
        // TODO: test emailId
    }

    /**
     * Test the property 'listId'
     */
    @Test
    public void listIdTest() {
        // TODO: test listId
    }

    /**
     * Test the property 'listIsActive'
     */
    @Test
    public void listIsActiveTest() {
        // TODO: test listIsActive
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'nextSend'
     */
    @Test
    public void nextSendTest() {
        // TODO: test nextSend
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
