/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.Contact;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SurveyQuestionAnswer
 */
class SurveyQuestionAnswerTest {
    private final SurveyQuestionAnswer model = new SurveyQuestionAnswer();

    /**
     * Model tests for SurveyQuestionAnswer
     */
    @Test
    void testSurveyQuestionAnswer() {
        // TODO: test SurveyQuestionAnswer
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'responseId'
     */
    @Test
    void responseIdTest() {
        // TODO: test responseId
    }

    /**
     * Test the property 'submittedAt'
     */
    @Test
    void submittedAtTest() {
        // TODO: test submittedAt
    }

    /**
     * Test the property 'contact'
     */
    @Test
    void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'isNewContact'
     */
    @Test
    void isNewContactTest() {
        // TODO: test isNewContact
    }

}
