/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.81
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for TrackingSettings
 */
public class TrackingSettingsTest {
    private final TrackingSettings model = new TrackingSettings();

    /**
     * Model tests for TrackingSettings
     */
    @Test
    public void testTrackingSettings() {
        // TODO: test TrackingSettings
    }

    /**
     * Test the property 'trackWithMailchimp'
     */
    @Test
    public void trackWithMailchimpTest() {
        // TODO: test trackWithMailchimp
    }

    /**
     * Test the property 'enableRestrictedDataProcessing'
     */
    @Test
    public void enableRestrictedDataProcessingTest() {
        // TODO: test enableRestrictedDataProcessing
    }

}
