/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.81
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.GroupA;
import io.github.erkoristhein.mailchimp.marketing.model.GroupB;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A breakdown of clicks by different groups of an A/B Split campaign. Does not return information about Multivariate Campaigns.
 */
@JsonPropertyOrder({
  ABSplit.JSON_PROPERTY_A,
  ABSplit.JSON_PROPERTY_B
})
@JsonTypeName("A_B_Split")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-03T13:08:30.305646+02:00[Europe/Tallinn]")
public class ABSplit {
  public static final String JSON_PROPERTY_A = "a";
  private GroupA a;

  public static final String JSON_PROPERTY_B = "b";
  private GroupB b;

  public ABSplit() {
  }

  public ABSplit a(GroupA a) {
    
    this.a = a;
    return this;
  }

   /**
   * Get a
   * @return a
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GroupA getA() {
    return a;
  }


  @JsonProperty(JSON_PROPERTY_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setA(GroupA a) {
    this.a = a;
  }


  public ABSplit b(GroupB b) {
    
    this.b = b;
    return this;
  }

   /**
   * Get b
   * @return b
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_B)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GroupB getB() {
    return b;
  }


  @JsonProperty(JSON_PROPERTY_B)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setB(GroupB b) {
    this.b = b;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ABSplit aBSplit = (ABSplit) o;
    return Objects.equals(this.a, aBSplit.a) &&
        Objects.equals(this.b, aBSplit.b);
  }

  @Override
  public int hashCode() {
    return Objects.hash(a, b);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ABSplit {\n");
    sb.append("    a: ").append(toIndentedString(a)).append("\n");
    sb.append("    b: ").append(toIndentedString(b)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

