/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ECommerceCartLineItem;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A collection of a cart&#39;s line items.
 */
@JsonPropertyOrder({
  CartLines.JSON_PROPERTY_STORE_ID,
  CartLines.JSON_PROPERTY_CART_ID,
  CartLines.JSON_PROPERTY_LINES,
  CartLines.JSON_PROPERTY_TOTAL_ITEMS,
  CartLines.JSON_PROPERTY_LINKS
})
@JsonTypeName("Cart_Lines")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-20T13:33:02.593663+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class CartLines {
  public static final String JSON_PROPERTY_STORE_ID = "store_id";
  @jakarta.annotation.Nullable
  private String storeId;

  public static final String JSON_PROPERTY_CART_ID = "cart_id";
  @jakarta.annotation.Nullable
  private String cartId;

  public static final String JSON_PROPERTY_LINES = "lines";
  @jakarta.annotation.Nullable
  private List<ECommerceCartLineItem> lines = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL_ITEMS = "total_items";
  @jakarta.annotation.Nullable
  private Integer totalItems;

  public static final String JSON_PROPERTY_LINKS = "_links";
  @jakarta.annotation.Nullable
  private List<ResourceLink> links = new ArrayList<>();

  public CartLines() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public CartLines(
    @JsonProperty(JSON_PROPERTY_TOTAL_ITEMS) Integer totalItems, 
    @JsonProperty(JSON_PROPERTY_LINKS) List<ResourceLink> links
  ) {
    this();
    this.totalItems = totalItems;
    this.links = links;
  }

  public CartLines storeId(@jakarta.annotation.Nullable String storeId) {
    
    this.storeId = storeId;
    return this;
  }

  /**
   * The store id.
   * @return storeId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STORE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStoreId() {
    return storeId;
  }


  @JsonProperty(value = JSON_PROPERTY_STORE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStoreId(@jakarta.annotation.Nullable String storeId) {
    this.storeId = storeId;
  }

  public CartLines cartId(@jakarta.annotation.Nullable String cartId) {
    
    this.cartId = cartId;
    return this;
  }

  /**
   * The cart id.
   * @return cartId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CART_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCartId() {
    return cartId;
  }


  @JsonProperty(value = JSON_PROPERTY_CART_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCartId(@jakarta.annotation.Nullable String cartId) {
    this.cartId = cartId;
  }

  public CartLines lines(@jakarta.annotation.Nullable List<ECommerceCartLineItem> lines) {
    
    this.lines = lines;
    return this;
  }

  public CartLines addLinesItem(ECommerceCartLineItem linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<>();
    }
    this.lines.add(linesItem);
    return this;
  }

  /**
   * An array of objects, each representing a cart&#39;s line item.
   * @return lines
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ECommerceCartLineItem> getLines() {
    return lines;
  }


  @JsonProperty(value = JSON_PROPERTY_LINES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLines(@jakarta.annotation.Nullable List<ECommerceCartLineItem> lines) {
    this.lines = lines;
  }

  /**
   * The total number of items matching the query regardless of pagination.
   * @return totalItems
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalItems() {
    return totalItems;
  }



  /**
   * A list of link types and descriptions for the API schema documents.
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResourceLink> getLinks() {
    return links;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartLines cartLines = (CartLines) o;
    return Objects.equals(this.storeId, cartLines.storeId) &&
        Objects.equals(this.cartId, cartLines.cartId) &&
        Objects.equals(this.lines, cartLines.lines) &&
        Objects.equals(this.totalItems, cartLines.totalItems) &&
        Objects.equals(this.links, cartLines.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storeId, cartId, lines, totalItems, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartLines {\n");
    sb.append("    storeId: ").append(toIndentedString(storeId)).append("\n");
    sb.append("    cartId: ").append(toIndentedString(cartId)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

