/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Information about a specific product image.
 */
@JsonPropertyOrder({
  ECommerceProductImage.JSON_PROPERTY_ID,
  ECommerceProductImage.JSON_PROPERTY_URL,
  ECommerceProductImage.JSON_PROPERTY_VARIANT_IDS
})
@JsonTypeName("E_commerce_Product_Image")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-20T13:33:02.593663+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class ECommerceProductImage {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nonnull
  private String url;

  public static final String JSON_PROPERTY_VARIANT_IDS = "variant_ids";
  @jakarta.annotation.Nullable
  private List<String> variantIds = new ArrayList<>();

  public ECommerceProductImage() {
  }

  public ECommerceProductImage id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * A unique identifier for the product image.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public ECommerceProductImage url(@jakarta.annotation.Nonnull String url) {
    
    this.url = url;
    return this;
  }

  /**
   * The URL for a product image.
   * @return url
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@jakarta.annotation.Nonnull String url) {
    this.url = url;
  }

  public ECommerceProductImage variantIds(@jakarta.annotation.Nullable List<String> variantIds) {
    
    this.variantIds = variantIds;
    return this;
  }

  public ECommerceProductImage addVariantIdsItem(String variantIdsItem) {
    if (this.variantIds == null) {
      this.variantIds = new ArrayList<>();
    }
    this.variantIds.add(variantIdsItem);
    return this;
  }

  /**
   * The list of product variants using the image.
   * @return variantIds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIANT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getVariantIds() {
    return variantIds;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIANT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariantIds(@jakarta.annotation.Nullable List<String> variantIds) {
    this.variantIds = variantIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ECommerceProductImage eCommerceProductImage = (ECommerceProductImage) o;
    return Objects.equals(this.id, eCommerceProductImage.id) &&
        Objects.equals(this.url, eCommerceProductImage.url) &&
        Objects.equals(this.variantIds, eCommerceProductImage.variantIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, variantIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ECommerceProductImage {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    variantIds: ").append(toIndentedString(variantIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

