/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.81
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.Address1;
import io.github.erkoristhein.mailchimp.marketing.model.Automations;
import io.github.erkoristhein.mailchimp.marketing.model.ConnectedSite2;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * An individual store in an account.
 */
@JsonPropertyOrder({
  ECommerceStore.JSON_PROPERTY_ID,
  ECommerceStore.JSON_PROPERTY_LIST_ID,
  ECommerceStore.JSON_PROPERTY_NAME,
  ECommerceStore.JSON_PROPERTY_PLATFORM,
  ECommerceStore.JSON_PROPERTY_DOMAIN,
  ECommerceStore.JSON_PROPERTY_IS_SYNCING,
  ECommerceStore.JSON_PROPERTY_EMAIL_ADDRESS,
  ECommerceStore.JSON_PROPERTY_CURRENCY_CODE,
  ECommerceStore.JSON_PROPERTY_MONEY_FORMAT,
  ECommerceStore.JSON_PROPERTY_PRIMARY_LOCALE,
  ECommerceStore.JSON_PROPERTY_TIMEZONE,
  ECommerceStore.JSON_PROPERTY_PHONE,
  ECommerceStore.JSON_PROPERTY_ADDRESS,
  ECommerceStore.JSON_PROPERTY_CONNECTED_SITE,
  ECommerceStore.JSON_PROPERTY_AUTOMATIONS,
  ECommerceStore.JSON_PROPERTY_LIST_IS_ACTIVE,
  ECommerceStore.JSON_PROPERTY_CREATED_AT,
  ECommerceStore.JSON_PROPERTY_UPDATED_AT,
  ECommerceStore.JSON_PROPERTY_LINKS
})
@JsonTypeName("E_commerce_Store")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-03T13:08:30.305646+02:00[Europe/Tallinn]")
public class ECommerceStore {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_LIST_ID = "list_id";
  private String listId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  private String platform;

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  private String domain;

  public static final String JSON_PROPERTY_IS_SYNCING = "is_syncing";
  private Boolean isSyncing;

  public static final String JSON_PROPERTY_EMAIL_ADDRESS = "email_address";
  private String emailAddress;

  public static final String JSON_PROPERTY_CURRENCY_CODE = "currency_code";
  private String currencyCode;

  public static final String JSON_PROPERTY_MONEY_FORMAT = "money_format";
  private String moneyFormat;

  public static final String JSON_PROPERTY_PRIMARY_LOCALE = "primary_locale";
  private String primaryLocale;

  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  private String timezone;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private Address1 address;

  public static final String JSON_PROPERTY_CONNECTED_SITE = "connected_site";
  private ConnectedSite2 connectedSite;

  public static final String JSON_PROPERTY_AUTOMATIONS = "automations";
  private Automations automations;

  public static final String JSON_PROPERTY_LIST_IS_ACTIVE = "list_is_active";
  private Boolean listIsActive;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_LINKS = "_links";
  private List<ResourceLink> links;

  public ECommerceStore() {
  }

  @JsonCreator
  public ECommerceStore(
    @JsonProperty(JSON_PROPERTY_ID) String id, 
    @JsonProperty(JSON_PROPERTY_LIST_ID) String listId, 
    @JsonProperty(JSON_PROPERTY_LIST_IS_ACTIVE) Boolean listIsActive, 
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt, 
    @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt, 
    @JsonProperty(JSON_PROPERTY_LINKS) List<ResourceLink> links
  ) {
    this();
    this.id = id;
    this.listId = listId;
    this.listIsActive = listIsActive;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.links = links;
  }

   /**
   * The unique identifier for the store.
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }




   /**
   * The unique identifier for the list that&#39;s associated with the store. The &#x60;list_id&#x60; for a specific store can&#39;t change.
   * @return listId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getListId() {
    return listId;
  }




  public ECommerceStore name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the store.
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ECommerceStore platform(String platform) {
    
    this.platform = platform;
    return this;
  }

   /**
   * The e-commerce platform of the store.
   * @return platform
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlatform() {
    return platform;
  }


  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatform(String platform) {
    this.platform = platform;
  }


  public ECommerceStore domain(String domain) {
    
    this.domain = domain;
    return this;
  }

   /**
   * The store domain.  The store domain must be unique within a user account.
   * @return domain
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDomain() {
    return domain;
  }


  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomain(String domain) {
    this.domain = domain;
  }


  public ECommerceStore isSyncing(Boolean isSyncing) {
    
    this.isSyncing = isSyncing;
    return this;
  }

   /**
   * Whether to disable automations because the store is currently [syncing](https://mailchimp.com/developer/marketing/docs/e-commerce/#pausing-store-automations).
   * @return isSyncing
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_SYNCING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSyncing() {
    return isSyncing;
  }


  @JsonProperty(JSON_PROPERTY_IS_SYNCING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSyncing(Boolean isSyncing) {
    this.isSyncing = isSyncing;
  }


  public ECommerceStore emailAddress(String emailAddress) {
    
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * The email address for the store.
   * @return emailAddress
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmailAddress() {
    return emailAddress;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }


  public ECommerceStore currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * The three-letter ISO 4217 code for the currency that the store accepts.
   * @return currencyCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrencyCode() {
    return currencyCode;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public ECommerceStore moneyFormat(String moneyFormat) {
    
    this.moneyFormat = moneyFormat;
    return this;
  }

   /**
   * The currency format for the store. For example: &#x60;$&#x60;, &#x60;£&#x60;, etc.
   * @return moneyFormat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MONEY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMoneyFormat() {
    return moneyFormat;
  }


  @JsonProperty(JSON_PROPERTY_MONEY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMoneyFormat(String moneyFormat) {
    this.moneyFormat = moneyFormat;
  }


  public ECommerceStore primaryLocale(String primaryLocale) {
    
    this.primaryLocale = primaryLocale;
    return this;
  }

   /**
   * The primary locale for the store. For example: &#x60;en&#x60;, &#x60;de&#x60;, etc.
   * @return primaryLocale
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRIMARY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrimaryLocale() {
    return primaryLocale;
  }


  @JsonProperty(JSON_PROPERTY_PRIMARY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrimaryLocale(String primaryLocale) {
    this.primaryLocale = primaryLocale;
  }


  public ECommerceStore timezone(String timezone) {
    
    this.timezone = timezone;
    return this;
  }

   /**
   * The timezone for the store.
   * @return timezone
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimezone() {
    return timezone;
  }


  @JsonProperty(JSON_PROPERTY_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  public ECommerceStore phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * The store phone number.
   * @return phone
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(String phone) {
    this.phone = phone;
  }


  public ECommerceStore address(Address1 address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Address1 getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(Address1 address) {
    this.address = address;
  }


  public ECommerceStore connectedSite(ConnectedSite2 connectedSite) {
    
    this.connectedSite = connectedSite;
    return this;
  }

   /**
   * Get connectedSite
   * @return connectedSite
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONNECTED_SITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConnectedSite2 getConnectedSite() {
    return connectedSite;
  }


  @JsonProperty(JSON_PROPERTY_CONNECTED_SITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConnectedSite(ConnectedSite2 connectedSite) {
    this.connectedSite = connectedSite;
  }


  public ECommerceStore automations(Automations automations) {
    
    this.automations = automations;
    return this;
  }

   /**
   * Get automations
   * @return automations
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTOMATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Automations getAutomations() {
    return automations;
  }


  @JsonProperty(JSON_PROPERTY_AUTOMATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutomations(Automations automations) {
    this.automations = automations;
  }


   /**
   * The status of the list connected to the store, namely if it&#39;s deleted or disabled.
   * @return listIsActive
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIST_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getListIsActive() {
    return listIsActive;
  }




   /**
   * The date and time the store was created in ISO 8601 format.
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * The date and time the store was last updated in ISO 8601 format.
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




   /**
   * A list of link types and descriptions for the API schema documents.
   * @return links
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResourceLink> getLinks() {
    return links;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ECommerceStore eCommerceStore = (ECommerceStore) o;
    return Objects.equals(this.id, eCommerceStore.id) &&
        Objects.equals(this.listId, eCommerceStore.listId) &&
        Objects.equals(this.name, eCommerceStore.name) &&
        Objects.equals(this.platform, eCommerceStore.platform) &&
        Objects.equals(this.domain, eCommerceStore.domain) &&
        Objects.equals(this.isSyncing, eCommerceStore.isSyncing) &&
        Objects.equals(this.emailAddress, eCommerceStore.emailAddress) &&
        Objects.equals(this.currencyCode, eCommerceStore.currencyCode) &&
        Objects.equals(this.moneyFormat, eCommerceStore.moneyFormat) &&
        Objects.equals(this.primaryLocale, eCommerceStore.primaryLocale) &&
        Objects.equals(this.timezone, eCommerceStore.timezone) &&
        Objects.equals(this.phone, eCommerceStore.phone) &&
        Objects.equals(this.address, eCommerceStore.address) &&
        Objects.equals(this.connectedSite, eCommerceStore.connectedSite) &&
        Objects.equals(this.automations, eCommerceStore.automations) &&
        Objects.equals(this.listIsActive, eCommerceStore.listIsActive) &&
        Objects.equals(this.createdAt, eCommerceStore.createdAt) &&
        Objects.equals(this.updatedAt, eCommerceStore.updatedAt) &&
        Objects.equals(this.links, eCommerceStore.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, listId, name, platform, domain, isSyncing, emailAddress, currencyCode, moneyFormat, primaryLocale, timezone, phone, address, connectedSite, automations, listIsActive, createdAt, updatedAt, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ECommerceStore {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    listId: ").append(toIndentedString(listId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    isSyncing: ").append(toIndentedString(isSyncing)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    moneyFormat: ").append(toIndentedString(moneyFormat)).append("\n");
    sb.append("    primaryLocale: ").append(toIndentedString(primaryLocale)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    connectedSite: ").append(toIndentedString(connectedSite)).append("\n");
    sb.append("    automations: ").append(toIndentedString(automations)).append("\n");
    sb.append("    listIsActive: ").append(toIndentedString(listIsActive)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

