/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Information about a specific cart line item.
 */
@JsonPropertyOrder({
  ECommerceCartLineItem.JSON_PROPERTY_ID,
  ECommerceCartLineItem.JSON_PROPERTY_PRODUCT_ID,
  ECommerceCartLineItem.JSON_PROPERTY_PRODUCT_TITLE,
  ECommerceCartLineItem.JSON_PROPERTY_PRODUCT_VARIANT_ID,
  ECommerceCartLineItem.JSON_PROPERTY_PRODUCT_VARIANT_TITLE,
  ECommerceCartLineItem.JSON_PROPERTY_QUANTITY,
  ECommerceCartLineItem.JSON_PROPERTY_PRICE,
  ECommerceCartLineItem.JSON_PROPERTY_LINKS
})
@JsonTypeName("E_commerce_Cart_Line_Item")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-20T12:12:19.705784+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class ECommerceCartLineItem {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  @jakarta.annotation.Nullable
  private String productId;

  public static final String JSON_PROPERTY_PRODUCT_TITLE = "product_title";
  @jakarta.annotation.Nullable
  private String productTitle;

  public static final String JSON_PROPERTY_PRODUCT_VARIANT_ID = "product_variant_id";
  @jakarta.annotation.Nullable
  private String productVariantId;

  public static final String JSON_PROPERTY_PRODUCT_VARIANT_TITLE = "product_variant_title";
  @jakarta.annotation.Nullable
  private String productVariantTitle;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @jakarta.annotation.Nullable
  private Integer quantity;

  public static final String JSON_PROPERTY_PRICE = "price";
  @jakarta.annotation.Nullable
  private BigDecimal price;

  public static final String JSON_PROPERTY_LINKS = "_links";
  @jakarta.annotation.Nullable
  private List<ResourceLink> links = new ArrayList<>();

  public ECommerceCartLineItem() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ECommerceCartLineItem(
    @JsonProperty(JSON_PROPERTY_ID) String id, 
    @JsonProperty(JSON_PROPERTY_PRODUCT_TITLE) String productTitle, 
    @JsonProperty(JSON_PROPERTY_PRODUCT_VARIANT_TITLE) String productVariantTitle, 
    @JsonProperty(JSON_PROPERTY_LINKS) List<ResourceLink> links
  ) {
    this();
    this.id = id;
    this.productTitle = productTitle;
    this.productVariantTitle = productVariantTitle;
    this.links = links;
  }

  /**
   * A unique identifier for the cart line item.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }



  public ECommerceCartLineItem productId(@jakarta.annotation.Nullable String productId) {
    
    this.productId = productId;
    return this;
  }

  /**
   * A unique identifier for the product associated with the cart line item.
   * @return productId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductId(@jakarta.annotation.Nullable String productId) {
    this.productId = productId;
  }

  /**
   * The name of the product for the cart line item.
   * @return productTitle
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductTitle() {
    return productTitle;
  }



  public ECommerceCartLineItem productVariantId(@jakarta.annotation.Nullable String productVariantId) {
    
    this.productVariantId = productVariantId;
    return this;
  }

  /**
   * A unique identifier for the product variant associated with the cart line item.
   * @return productVariantId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_VARIANT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductVariantId() {
    return productVariantId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_VARIANT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductVariantId(@jakarta.annotation.Nullable String productVariantId) {
    this.productVariantId = productVariantId;
  }

  /**
   * The name of the product variant for the cart line item.
   * @return productVariantTitle
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_VARIANT_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductVariantTitle() {
    return productVariantTitle;
  }



  public ECommerceCartLineItem quantity(@jakarta.annotation.Nullable Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

  /**
   * The quantity of a cart line item.
   * @return quantity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(@jakarta.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
  }

  public ECommerceCartLineItem price(@jakarta.annotation.Nullable BigDecimal price) {
    
    this.price = price;
    return this;
  }

  /**
   * The price of a cart line item.
   * @return price
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(@jakarta.annotation.Nullable BigDecimal price) {
    this.price = price;
  }

  /**
   * A list of link types and descriptions for the API schema documents.
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResourceLink> getLinks() {
    return links;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ECommerceCartLineItem eCommerceCartLineItem = (ECommerceCartLineItem) o;
    return Objects.equals(this.id, eCommerceCartLineItem.id) &&
        Objects.equals(this.productId, eCommerceCartLineItem.productId) &&
        Objects.equals(this.productTitle, eCommerceCartLineItem.productTitle) &&
        Objects.equals(this.productVariantId, eCommerceCartLineItem.productVariantId) &&
        Objects.equals(this.productVariantTitle, eCommerceCartLineItem.productVariantTitle) &&
        Objects.equals(this.quantity, eCommerceCartLineItem.quantity) &&
        Objects.equals(this.price, eCommerceCartLineItem.price) &&
        Objects.equals(this.links, eCommerceCartLineItem.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, productId, productTitle, productVariantId, productVariantTitle, quantity, price, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ECommerceCartLineItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    productTitle: ").append(toIndentedString(productTitle)).append("\n");
    sb.append("    productVariantId: ").append(toIndentedString(productVariantId)).append("\n");
    sb.append("    productVariantTitle: ").append(toIndentedString(productVariantTitle)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

