/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.Address;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Information about a specific customer. For existing customers include only the &#x60;id&#x60; parameter in the &#x60;customer&#x60; object body.
 */
@JsonPropertyOrder({
  ECommerceCustomer1.JSON_PROPERTY_ID,
  ECommerceCustomer1.JSON_PROPERTY_EMAIL_ADDRESS,
  ECommerceCustomer1.JSON_PROPERTY_OPT_IN_STATUS,
  ECommerceCustomer1.JSON_PROPERTY_COMPANY,
  ECommerceCustomer1.JSON_PROPERTY_FIRST_NAME,
  ECommerceCustomer1.JSON_PROPERTY_LAST_NAME,
  ECommerceCustomer1.JSON_PROPERTY_ADDRESS
})
@JsonTypeName("E_commerce_Customer_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-23T15:30:38.569460+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class ECommerceCustomer1 {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_EMAIL_ADDRESS = "email_address";
  @jakarta.annotation.Nullable
  private String emailAddress;

  public static final String JSON_PROPERTY_OPT_IN_STATUS = "opt_in_status";
  @jakarta.annotation.Nullable
  private Boolean optInStatus;

  public static final String JSON_PROPERTY_COMPANY = "company";
  @jakarta.annotation.Nullable
  private String company;

  public static final String JSON_PROPERTY_FIRST_NAME = "first_name";
  @jakarta.annotation.Nullable
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "last_name";
  @jakarta.annotation.Nullable
  private String lastName;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nullable
  private Address address;

  public ECommerceCustomer1() {
  }

  public ECommerceCustomer1 id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * A unique identifier for the customer. Limited to 50 characters.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public ECommerceCustomer1 emailAddress(@jakarta.annotation.Nullable String emailAddress) {
    
    this.emailAddress = emailAddress;
    return this;
  }

  /**
   * The customer&#39;s email address.
   * @return emailAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmailAddress() {
    return emailAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailAddress(@jakarta.annotation.Nullable String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public ECommerceCustomer1 optInStatus(@jakarta.annotation.Nullable Boolean optInStatus) {
    
    this.optInStatus = optInStatus;
    return this;
  }

  /**
   * The customer&#39;s opt-in status. This value will never overwrite the opt-in status of a pre-existing Mailchimp list member, but will apply to list members that are added through the e-commerce API endpoints. Customers who don&#39;t opt in to your Mailchimp list [will be added as &#x60;Transactional&#x60; members](https://mailchimp.com/developer/marketing/docs/e-commerce/#customers).
   * @return optInStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPT_IN_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOptInStatus() {
    return optInStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_OPT_IN_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOptInStatus(@jakarta.annotation.Nullable Boolean optInStatus) {
    this.optInStatus = optInStatus;
  }

  public ECommerceCustomer1 company(@jakarta.annotation.Nullable String company) {
    
    this.company = company;
    return this;
  }

  /**
   * The customer&#39;s company.
   * @return company
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPANY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCompany() {
    return company;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPANY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompany(@jakarta.annotation.Nullable String company) {
    this.company = company;
  }

  public ECommerceCustomer1 firstName(@jakarta.annotation.Nullable String firstName) {
    
    this.firstName = firstName;
    return this;
  }

  /**
   * The customer&#39;s first name.
   * @return firstName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(@jakarta.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }

  public ECommerceCustomer1 lastName(@jakarta.annotation.Nullable String lastName) {
    
    this.lastName = lastName;
    return this;
  }

  /**
   * The customer&#39;s last name.
   * @return lastName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = lastName;
  }

  public ECommerceCustomer1 address(@jakarta.annotation.Nullable Address address) {
    
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Address getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@jakarta.annotation.Nullable Address address) {
    this.address = address;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ECommerceCustomer1 eCommerceCustomer1 = (ECommerceCustomer1) o;
    return Objects.equals(this.id, eCommerceCustomer1.id) &&
        Objects.equals(this.emailAddress, eCommerceCustomer1.emailAddress) &&
        Objects.equals(this.optInStatus, eCommerceCustomer1.optInStatus) &&
        Objects.equals(this.company, eCommerceCustomer1.company) &&
        Objects.equals(this.firstName, eCommerceCustomer1.firstName) &&
        Objects.equals(this.lastName, eCommerceCustomer1.lastName) &&
        Objects.equals(this.address, eCommerceCustomer1.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, emailAddress, optInStatus, company, firstName, lastName, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ECommerceCustomer1 {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    optInStatus: ").append(toIndentedString(optInStatus)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

