/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * An individual file listed in the File Manager.
 */
@JsonPropertyOrder({
  GalleryFile1.JSON_PROPERTY_FOLDER_ID,
  GalleryFile1.JSON_PROPERTY_NAME,
  GalleryFile1.JSON_PROPERTY_FILE_DATA
})
@JsonTypeName("Gallery_File_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-23T15:30:38.569460+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class GalleryFile1 {
  public static final String JSON_PROPERTY_FOLDER_ID = "folder_id";
  @jakarta.annotation.Nullable
  private Integer folderId;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_FILE_DATA = "file_data";
  @jakarta.annotation.Nonnull
  private String fileData;

  public GalleryFile1() {
  }

  public GalleryFile1 folderId(@jakarta.annotation.Nullable Integer folderId) {
    
    this.folderId = folderId;
    return this;
  }

  /**
   * The id of the folder.
   * @return folderId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FOLDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFolderId() {
    return folderId;
  }


  @JsonProperty(value = JSON_PROPERTY_FOLDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFolderId(@jakarta.annotation.Nullable Integer folderId) {
    this.folderId = folderId;
  }

  public GalleryFile1 name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the file.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public GalleryFile1 fileData(@jakarta.annotation.Nonnull String fileData) {
    
    this.fileData = fileData;
    return this;
  }

  /**
   * The base64-encoded contents of the file.
   * @return fileData
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FILE_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFileData() {
    return fileData;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileData(@jakarta.annotation.Nonnull String fileData) {
    this.fileData = fileData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GalleryFile1 galleryFile1 = (GalleryFile1) o;
    return Objects.equals(this.folderId, galleryFile1.folderId) &&
        Objects.equals(this.name, galleryFile1.name) &&
        Objects.equals(this.fileData, galleryFile1.fileData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folderId, name, fileData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GalleryFile1 {\n");
    sb.append("    folderId: ").append(toIndentedString(folderId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fileData: ").append(toIndentedString(fileData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

