/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudience;
import io.github.erkoristhein.mailchimp.marketing.model.GetAllFacebookAds200ResponseFacebookAdsInnerAllOfBudget;
import io.github.erkoristhein.mailchimp.marketing.model.GetAllFacebookAds200ResponseFacebookAdsInnerAllOfChannel;
import io.github.erkoristhein.mailchimp.marketing.model.GetAllFacebookAds200ResponseFacebookAdsInnerAllOfContent;
import io.github.erkoristhein.mailchimp.marketing.model.GetAllFacebookAds200ResponseFacebookAdsInnerAllOfFeedback;
import io.github.erkoristhein.mailchimp.marketing.model.GetAllFacebookAds200ResponseFacebookAdsInnerAllOfSite;
import io.github.erkoristhein.mailchimp.marketing.model.Recipients;
import io.github.erkoristhein.mailchimp.marketing.model.ReportSummary;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetFacebookAdsId200Response
 */
@JsonPropertyOrder({
  GetFacebookAdsId200Response.JSON_PROPERTY_ID,
  GetFacebookAdsId200Response.JSON_PROPERTY_WEB_ID,
  GetFacebookAdsId200Response.JSON_PROPERTY_NAME,
  GetFacebookAdsId200Response.JSON_PROPERTY_TYPE,
  GetFacebookAdsId200Response.JSON_PROPERTY_STATUS,
  GetFacebookAdsId200Response.JSON_PROPERTY_SHOW_REPORT,
  GetFacebookAdsId200Response.JSON_PROPERTY_CREATE_TIME,
  GetFacebookAdsId200Response.JSON_PROPERTY_START_TIME,
  GetFacebookAdsId200Response.JSON_PROPERTY_UPDATED_AT,
  GetFacebookAdsId200Response.JSON_PROPERTY_CANCELED_AT,
  GetFacebookAdsId200Response.JSON_PROPERTY_PUBLISHED_TIME,
  GetFacebookAdsId200Response.JSON_PROPERTY_HAS_SEGMENT,
  GetFacebookAdsId200Response.JSON_PROPERTY_REPORT_SUMMARY,
  GetFacebookAdsId200Response.JSON_PROPERTY_RECIPIENTS,
  GetFacebookAdsId200Response.JSON_PROPERTY_THUMBNAIL,
  GetFacebookAdsId200Response.JSON_PROPERTY_EMAIL_SOURCE_NAME,
  GetFacebookAdsId200Response.JSON_PROPERTY_PAUSED_AT,
  GetFacebookAdsId200Response.JSON_PROPERTY_END_TIME,
  GetFacebookAdsId200Response.JSON_PROPERTY_NEEDS_ATTENTION,
  GetFacebookAdsId200Response.JSON_PROPERTY_WAS_CANCELED_BY_FACEBOOK,
  GetFacebookAdsId200Response.JSON_PROPERTY_IS_CONNECTED,
  GetFacebookAdsId200Response.JSON_PROPERTY_HAS_AUDIENCE,
  GetFacebookAdsId200Response.JSON_PROPERTY_HAS_CONTENT,
  GetFacebookAdsId200Response.JSON_PROPERTY_CHANNEL,
  GetFacebookAdsId200Response.JSON_PROPERTY_FEEDBACK,
  GetFacebookAdsId200Response.JSON_PROPERTY_SITE,
  GetFacebookAdsId200Response.JSON_PROPERTY_AUDIENCE,
  GetFacebookAdsId200Response.JSON_PROPERTY_BUDGET,
  GetFacebookAdsId200Response.JSON_PROPERTY_CONTENT,
  GetFacebookAdsId200Response.JSON_PROPERTY_LINKS
})
@JsonTypeName("getFacebookAdsId_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-20T13:33:02.593663+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class GetFacebookAdsId200Response {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_WEB_ID = "web_id";
  @jakarta.annotation.Nullable
  private Integer webId;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  /**
   * The type of outreach this object is.
   */
  public enum TypeEnum {
    REGULAR(String.valueOf("regular")),
    
    EMAIL_TOUCHPOINT(String.valueOf("email-touchpoint")),
    
    PLAINTEXT(String.valueOf("plaintext")),
    
    RSS(String.valueOf("rss")),
    
    RECONFIRM(String.valueOf("reconfirm")),
    
    VARIATE(String.valueOf("variate")),
    
    ABSPLIT(String.valueOf("absplit")),
    
    AUTOMATION(String.valueOf("automation")),
    
    FACEBOOK(String.valueOf("facebook")),
    
    GOOGLE(String.valueOf("google")),
    
    AUTORESPONDER(String.valueOf("autoresponder")),
    
    TRANSACTIONAL(String.valueOf("transactional")),
    
    PAGE(String.valueOf("page")),
    
    WEBSITE(String.valueOf("website")),
    
    SOCIAL_POST(String.valueOf("social_post")),
    
    SURVEY(String.valueOf("survey")),
    
    CUSTOMER_JOURNEY(String.valueOf("customer_journey")),
    
    SMS(String.valueOf("sms"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  /**
   * The status of this outreach.
   */
  public enum StatusEnum {
    SAVE(String.valueOf("save")),
    
    PAUSED(String.valueOf("paused")),
    
    SCHEDULE(String.valueOf("schedule")),
    
    SCHEDULED(String.valueOf("scheduled")),
    
    SENDING(String.valueOf("sending")),
    
    SENT(String.valueOf("sent")),
    
    CANCELED(String.valueOf("canceled")),
    
    CANCELING(String.valueOf("canceling")),
    
    ACTIVE(String.valueOf("active")),
    
    DISCONNECTED(String.valueOf("disconnected")),
    
    SOMEPAUSED(String.valueOf("somepaused")),
    
    DRAFT(String.valueOf("draft")),
    
    COMPLETED(String.valueOf("completed")),
    
    PARTIAL_REJECTED(String.valueOf("partialRejected")),
    
    PENDING(String.valueOf("pending")),
    
    REJECTED(String.valueOf("rejected")),
    
    PUBLISHED(String.valueOf("published")),
    
    UNPUBLISHED(String.valueOf("unpublished"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_SHOW_REPORT = "show_report";
  @jakarta.annotation.Nullable
  private Boolean showReport;

  public static final String JSON_PROPERTY_CREATE_TIME = "create_time";
  @jakarta.annotation.Nullable
  private OffsetDateTime createTime;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @jakarta.annotation.Nullable
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_CANCELED_AT = "canceled_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime canceledAt;

  public static final String JSON_PROPERTY_PUBLISHED_TIME = "published_time";
  @jakarta.annotation.Nullable
  private OffsetDateTime publishedTime;

  public static final String JSON_PROPERTY_HAS_SEGMENT = "has_segment";
  @jakarta.annotation.Nullable
  private Boolean hasSegment;

  public static final String JSON_PROPERTY_REPORT_SUMMARY = "report_summary";
  @jakarta.annotation.Nullable
  private ReportSummary reportSummary;

  public static final String JSON_PROPERTY_RECIPIENTS = "recipients";
  @jakarta.annotation.Nullable
  private Recipients recipients;

  public static final String JSON_PROPERTY_THUMBNAIL = "thumbnail";
  @jakarta.annotation.Nullable
  private String thumbnail;

  public static final String JSON_PROPERTY_EMAIL_SOURCE_NAME = "email_source_name";
  @jakarta.annotation.Nullable
  private String emailSourceName;

  public static final String JSON_PROPERTY_PAUSED_AT = "paused_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime pausedAt;

  public static final String JSON_PROPERTY_END_TIME = "end_time";
  @jakarta.annotation.Nullable
  private OffsetDateTime endTime;

  public static final String JSON_PROPERTY_NEEDS_ATTENTION = "needs_attention";
  @jakarta.annotation.Nullable
  private Boolean needsAttention;

  public static final String JSON_PROPERTY_WAS_CANCELED_BY_FACEBOOK = "was_canceled_by_facebook";
  @jakarta.annotation.Nullable
  private Boolean wasCanceledByFacebook;

  public static final String JSON_PROPERTY_IS_CONNECTED = "is_connected";
  @jakarta.annotation.Nullable
  private Boolean isConnected;

  public static final String JSON_PROPERTY_HAS_AUDIENCE = "has_audience";
  @jakarta.annotation.Nullable
  private Boolean hasAudience;

  public static final String JSON_PROPERTY_HAS_CONTENT = "has_content";
  @jakarta.annotation.Nullable
  private Boolean hasContent;

  public static final String JSON_PROPERTY_CHANNEL = "channel";
  @jakarta.annotation.Nullable
  private GetAllFacebookAds200ResponseFacebookAdsInnerAllOfChannel channel;

  public static final String JSON_PROPERTY_FEEDBACK = "feedback";
  @jakarta.annotation.Nullable
  private GetAllFacebookAds200ResponseFacebookAdsInnerAllOfFeedback feedback;

  public static final String JSON_PROPERTY_SITE = "site";
  @jakarta.annotation.Nullable
  private GetAllFacebookAds200ResponseFacebookAdsInnerAllOfSite site;

  public static final String JSON_PROPERTY_AUDIENCE = "audience";
  @jakarta.annotation.Nullable
  private GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudience audience;

  public static final String JSON_PROPERTY_BUDGET = "budget";
  @jakarta.annotation.Nullable
  private GetAllFacebookAds200ResponseFacebookAdsInnerAllOfBudget budget;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @jakarta.annotation.Nullable
  private GetAllFacebookAds200ResponseFacebookAdsInnerAllOfContent content;

  public static final String JSON_PROPERTY_LINKS = "_links";
  @jakarta.annotation.Nullable
  private List<ResourceLink> links = new ArrayList<>();

  public GetFacebookAdsId200Response() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public GetFacebookAdsId200Response(
    @JsonProperty(JSON_PROPERTY_LINKS) List<ResourceLink> links
  ) {
    this();
    this.links = links;
  }

  public GetFacebookAdsId200Response id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique ID of an Outreach.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public GetFacebookAdsId200Response webId(@jakarta.annotation.Nullable Integer webId) {
    
    this.webId = webId;
    return this;
  }

  /**
   * The ID used in the Mailchimp web application. For example, for a &#x60;regular&#x60; outreach, you can view this campaign in your Mailchimp account at &#x60;https://{dc}.admin.mailchimp.com/campaigns/show/?id&#x3D;{web_id}&#x60;.
   * @return webId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEB_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWebId() {
    return webId;
  }


  @JsonProperty(value = JSON_PROPERTY_WEB_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebId(@jakarta.annotation.Nullable Integer webId) {
    this.webId = webId;
  }

  public GetFacebookAdsId200Response name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Title or name of an Outreach.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public GetFacebookAdsId200Response type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * The type of outreach this object is.
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  public GetFacebookAdsId200Response status(@jakarta.annotation.Nullable StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * The status of this outreach.
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
  }

  public GetFacebookAdsId200Response showReport(@jakarta.annotation.Nullable Boolean showReport) {
    
    this.showReport = showReport;
    return this;
  }

  /**
   * Outreach report availability. Note: This property is hotly debated in what it _should_ convey. See [MCP-1371](https://jira.mailchimp.com/browse/MCP-1371) for more context.
   * @return showReport
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOW_REPORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShowReport() {
    return showReport;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOW_REPORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowReport(@jakarta.annotation.Nullable Boolean showReport) {
    this.showReport = showReport;
  }

  public GetFacebookAdsId200Response createTime(@jakarta.annotation.Nullable OffsetDateTime createTime) {
    
    this.createTime = createTime;
    return this;
  }

  /**
   * The date and time the outreach was created in ISO 8601 format.
   * @return createTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreateTime() {
    return createTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateTime(@jakarta.annotation.Nullable OffsetDateTime createTime) {
    this.createTime = createTime;
  }

  public GetFacebookAdsId200Response startTime(@jakarta.annotation.Nullable OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

  /**
   * The date and time the outreach was started in ISO 8601 format.
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public GetFacebookAdsId200Response updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * The date and time the outreach was last updated in ISO 8601 format.
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public GetFacebookAdsId200Response canceledAt(@jakarta.annotation.Nullable OffsetDateTime canceledAt) {
    
    this.canceledAt = canceledAt;
    return this;
  }

  /**
   * The date and time the outreach was canceled in ISO 8601 format.
   * @return canceledAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CANCELED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCanceledAt() {
    return canceledAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CANCELED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanceledAt(@jakarta.annotation.Nullable OffsetDateTime canceledAt) {
    this.canceledAt = canceledAt;
  }

  public GetFacebookAdsId200Response publishedTime(@jakarta.annotation.Nullable OffsetDateTime publishedTime) {
    
    this.publishedTime = publishedTime;
    return this;
  }

  /**
   * The date and time the outreach was (or will be) published in ISO 8601 format.
   * @return publishedTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PUBLISHED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPublishedTime() {
    return publishedTime;
  }


  @JsonProperty(value = JSON_PROPERTY_PUBLISHED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishedTime(@jakarta.annotation.Nullable OffsetDateTime publishedTime) {
    this.publishedTime = publishedTime;
  }

  public GetFacebookAdsId200Response hasSegment(@jakarta.annotation.Nullable Boolean hasSegment) {
    
    this.hasSegment = hasSegment;
    return this;
  }

  /**
   * If this outreach targets a segment of your audience.
   * @return hasSegment
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_SEGMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasSegment() {
    return hasSegment;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_SEGMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasSegment(@jakarta.annotation.Nullable Boolean hasSegment) {
    this.hasSegment = hasSegment;
  }

  public GetFacebookAdsId200Response reportSummary(@jakarta.annotation.Nullable ReportSummary reportSummary) {
    
    this.reportSummary = reportSummary;
    return this;
  }

  /**
   * Get reportSummary
   * @return reportSummary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPORT_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReportSummary getReportSummary() {
    return reportSummary;
  }


  @JsonProperty(value = JSON_PROPERTY_REPORT_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportSummary(@jakarta.annotation.Nullable ReportSummary reportSummary) {
    this.reportSummary = reportSummary;
  }

  public GetFacebookAdsId200Response recipients(@jakarta.annotation.Nullable Recipients recipients) {
    
    this.recipients = recipients;
    return this;
  }

  /**
   * Get recipients
   * @return recipients
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECIPIENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Recipients getRecipients() {
    return recipients;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecipients(@jakarta.annotation.Nullable Recipients recipients) {
    this.recipients = recipients;
  }

  public GetFacebookAdsId200Response thumbnail(@jakarta.annotation.Nullable String thumbnail) {
    
    this.thumbnail = thumbnail;
    return this;
  }

  /**
   * The URL of the thumbnail for this outreach.
   * @return thumbnail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THUMBNAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getThumbnail() {
    return thumbnail;
  }


  @JsonProperty(value = JSON_PROPERTY_THUMBNAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThumbnail(@jakarta.annotation.Nullable String thumbnail) {
    this.thumbnail = thumbnail;
  }

  public GetFacebookAdsId200Response emailSourceName(@jakarta.annotation.Nullable String emailSourceName) {
    
    this.emailSourceName = emailSourceName;
    return this;
  }

  /**
   * Get emailSourceName
   * @return emailSourceName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL_SOURCE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmailSourceName() {
    return emailSourceName;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL_SOURCE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailSourceName(@jakarta.annotation.Nullable String emailSourceName) {
    this.emailSourceName = emailSourceName;
  }

  public GetFacebookAdsId200Response pausedAt(@jakarta.annotation.Nullable OffsetDateTime pausedAt) {
    
    this.pausedAt = pausedAt;
    return this;
  }

  /**
   * The date and time the ad was paused in ISO 8601 format.
   * @return pausedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAUSED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPausedAt() {
    return pausedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_PAUSED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPausedAt(@jakarta.annotation.Nullable OffsetDateTime pausedAt) {
    this.pausedAt = pausedAt;
  }

  public GetFacebookAdsId200Response endTime(@jakarta.annotation.Nullable OffsetDateTime endTime) {
    
    this.endTime = endTime;
    return this;
  }

  /**
   * The date and time the ad was ended in ISO 8601 format.
   * @return endTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEndTime() {
    return endTime;
  }


  @JsonProperty(value = JSON_PROPERTY_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(@jakarta.annotation.Nullable OffsetDateTime endTime) {
    this.endTime = endTime;
  }

  public GetFacebookAdsId200Response needsAttention(@jakarta.annotation.Nullable Boolean needsAttention) {
    
    this.needsAttention = needsAttention;
    return this;
  }

  /**
   * If the ad has a problem and needs attention.
   * @return needsAttention
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEEDS_ATTENTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNeedsAttention() {
    return needsAttention;
  }


  @JsonProperty(value = JSON_PROPERTY_NEEDS_ATTENTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNeedsAttention(@jakarta.annotation.Nullable Boolean needsAttention) {
    this.needsAttention = needsAttention;
  }

  public GetFacebookAdsId200Response wasCanceledByFacebook(@jakarta.annotation.Nullable Boolean wasCanceledByFacebook) {
    
    this.wasCanceledByFacebook = wasCanceledByFacebook;
    return this;
  }

  /**
   * Get wasCanceledByFacebook
   * @return wasCanceledByFacebook
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WAS_CANCELED_BY_FACEBOOK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getWasCanceledByFacebook() {
    return wasCanceledByFacebook;
  }


  @JsonProperty(value = JSON_PROPERTY_WAS_CANCELED_BY_FACEBOOK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWasCanceledByFacebook(@jakarta.annotation.Nullable Boolean wasCanceledByFacebook) {
    this.wasCanceledByFacebook = wasCanceledByFacebook;
  }

  public GetFacebookAdsId200Response isConnected(@jakarta.annotation.Nullable Boolean isConnected) {
    
    this.isConnected = isConnected;
    return this;
  }

  /**
   * Check if this ad is connected to a facebook page
   * @return isConnected
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_CONNECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsConnected() {
    return isConnected;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_CONNECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsConnected(@jakarta.annotation.Nullable Boolean isConnected) {
    this.isConnected = isConnected;
  }

  public GetFacebookAdsId200Response hasAudience(@jakarta.annotation.Nullable Boolean hasAudience) {
    
    this.hasAudience = hasAudience;
    return this;
  }

  /**
   * Check if this ad has audience setup
   * @return hasAudience
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_AUDIENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasAudience() {
    return hasAudience;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_AUDIENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasAudience(@jakarta.annotation.Nullable Boolean hasAudience) {
    this.hasAudience = hasAudience;
  }

  public GetFacebookAdsId200Response hasContent(@jakarta.annotation.Nullable Boolean hasContent) {
    
    this.hasContent = hasContent;
    return this;
  }

  /**
   * Check if this ad has content
   * @return hasContent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasContent() {
    return hasContent;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasContent(@jakarta.annotation.Nullable Boolean hasContent) {
    this.hasContent = hasContent;
  }

  public GetFacebookAdsId200Response channel(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfChannel channel) {
    
    this.channel = channel;
    return this;
  }

  /**
   * Get channel
   * @return channel
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANNEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetAllFacebookAds200ResponseFacebookAdsInnerAllOfChannel getChannel() {
    return channel;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANNEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChannel(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfChannel channel) {
    this.channel = channel;
  }

  public GetFacebookAdsId200Response feedback(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfFeedback feedback) {
    
    this.feedback = feedback;
    return this;
  }

  /**
   * Get feedback
   * @return feedback
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FEEDBACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetAllFacebookAds200ResponseFacebookAdsInnerAllOfFeedback getFeedback() {
    return feedback;
  }


  @JsonProperty(value = JSON_PROPERTY_FEEDBACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeedback(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfFeedback feedback) {
    this.feedback = feedback;
  }

  public GetFacebookAdsId200Response site(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfSite site) {
    
    this.site = site;
    return this;
  }

  /**
   * Get site
   * @return site
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetAllFacebookAds200ResponseFacebookAdsInnerAllOfSite getSite() {
    return site;
  }


  @JsonProperty(value = JSON_PROPERTY_SITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSite(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfSite site) {
    this.site = site;
  }

  public GetFacebookAdsId200Response audience(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudience audience) {
    
    this.audience = audience;
    return this;
  }

  /**
   * Get audience
   * @return audience
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUDIENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudience getAudience() {
    return audience;
  }


  @JsonProperty(value = JSON_PROPERTY_AUDIENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAudience(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudience audience) {
    this.audience = audience;
  }

  public GetFacebookAdsId200Response budget(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfBudget budget) {
    
    this.budget = budget;
    return this;
  }

  /**
   * Get budget
   * @return budget
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUDGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetAllFacebookAds200ResponseFacebookAdsInnerAllOfBudget getBudget() {
    return budget;
  }


  @JsonProperty(value = JSON_PROPERTY_BUDGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBudget(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfBudget budget) {
    this.budget = budget;
  }

  public GetFacebookAdsId200Response content(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfContent content) {
    
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetAllFacebookAds200ResponseFacebookAdsInnerAllOfContent getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(@jakarta.annotation.Nullable GetAllFacebookAds200ResponseFacebookAdsInnerAllOfContent content) {
    this.content = content;
  }

  /**
   * A list of link types and descriptions for the API schema documents.
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResourceLink> getLinks() {
    return links;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFacebookAdsId200Response getFacebookAdsId200Response = (GetFacebookAdsId200Response) o;
    return Objects.equals(this.id, getFacebookAdsId200Response.id) &&
        Objects.equals(this.webId, getFacebookAdsId200Response.webId) &&
        Objects.equals(this.name, getFacebookAdsId200Response.name) &&
        Objects.equals(this.type, getFacebookAdsId200Response.type) &&
        Objects.equals(this.status, getFacebookAdsId200Response.status) &&
        Objects.equals(this.showReport, getFacebookAdsId200Response.showReport) &&
        Objects.equals(this.createTime, getFacebookAdsId200Response.createTime) &&
        Objects.equals(this.startTime, getFacebookAdsId200Response.startTime) &&
        Objects.equals(this.updatedAt, getFacebookAdsId200Response.updatedAt) &&
        Objects.equals(this.canceledAt, getFacebookAdsId200Response.canceledAt) &&
        Objects.equals(this.publishedTime, getFacebookAdsId200Response.publishedTime) &&
        Objects.equals(this.hasSegment, getFacebookAdsId200Response.hasSegment) &&
        Objects.equals(this.reportSummary, getFacebookAdsId200Response.reportSummary) &&
        Objects.equals(this.recipients, getFacebookAdsId200Response.recipients) &&
        Objects.equals(this.thumbnail, getFacebookAdsId200Response.thumbnail) &&
        Objects.equals(this.emailSourceName, getFacebookAdsId200Response.emailSourceName) &&
        Objects.equals(this.pausedAt, getFacebookAdsId200Response.pausedAt) &&
        Objects.equals(this.endTime, getFacebookAdsId200Response.endTime) &&
        Objects.equals(this.needsAttention, getFacebookAdsId200Response.needsAttention) &&
        Objects.equals(this.wasCanceledByFacebook, getFacebookAdsId200Response.wasCanceledByFacebook) &&
        Objects.equals(this.isConnected, getFacebookAdsId200Response.isConnected) &&
        Objects.equals(this.hasAudience, getFacebookAdsId200Response.hasAudience) &&
        Objects.equals(this.hasContent, getFacebookAdsId200Response.hasContent) &&
        Objects.equals(this.channel, getFacebookAdsId200Response.channel) &&
        Objects.equals(this.feedback, getFacebookAdsId200Response.feedback) &&
        Objects.equals(this.site, getFacebookAdsId200Response.site) &&
        Objects.equals(this.audience, getFacebookAdsId200Response.audience) &&
        Objects.equals(this.budget, getFacebookAdsId200Response.budget) &&
        Objects.equals(this.content, getFacebookAdsId200Response.content) &&
        Objects.equals(this.links, getFacebookAdsId200Response.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, webId, name, type, status, showReport, createTime, startTime, updatedAt, canceledAt, publishedTime, hasSegment, reportSummary, recipients, thumbnail, emailSourceName, pausedAt, endTime, needsAttention, wasCanceledByFacebook, isConnected, hasAudience, hasContent, channel, feedback, site, audience, budget, content, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFacebookAdsId200Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    webId: ").append(toIndentedString(webId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    showReport: ").append(toIndentedString(showReport)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    canceledAt: ").append(toIndentedString(canceledAt)).append("\n");
    sb.append("    publishedTime: ").append(toIndentedString(publishedTime)).append("\n");
    sb.append("    hasSegment: ").append(toIndentedString(hasSegment)).append("\n");
    sb.append("    reportSummary: ").append(toIndentedString(reportSummary)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    emailSourceName: ").append(toIndentedString(emailSourceName)).append("\n");
    sb.append("    pausedAt: ").append(toIndentedString(pausedAt)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    needsAttention: ").append(toIndentedString(needsAttention)).append("\n");
    sb.append("    wasCanceledByFacebook: ").append(toIndentedString(wasCanceledByFacebook)).append("\n");
    sb.append("    isConnected: ").append(toIndentedString(isConnected)).append("\n");
    sb.append("    hasAudience: ").append(toIndentedString(hasAudience)).append("\n");
    sb.append("    hasContent: ").append(toIndentedString(hasContent)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    feedback: ").append(toIndentedString(feedback)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("    audience: ").append(toIndentedString(audience)).append("\n");
    sb.append("    budget: ").append(toIndentedString(budget)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

