/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner
 */
@JsonPropertyOrder({
  GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner.JSON_PROPERTY_DATE,
  GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner.JSON_PROPERTY_REVENUE
})
@JsonTypeName("getReportingFacebookAds_200_response_facebook_ads_inner_allOf_audience_activity_revenue_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T16:39:59.516441+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner {
  public static final String JSON_PROPERTY_DATE = "date";
  private String date;

  public static final String JSON_PROPERTY_REVENUE = "revenue";
  private BigDecimal revenue;

  public GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner() {
  }

  public GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner date(String date) {
    
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDate() {
    return date;
  }


  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate(String date) {
    this.date = date;
  }


  public GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner revenue(BigDecimal revenue) {
    
    this.revenue = revenue;
    return this;
  }

   /**
   * Get revenue
   * @return revenue
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRevenue() {
    return revenue;
  }


  @JsonProperty(JSON_PROPERTY_REVENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevenue(BigDecimal revenue) {
    this.revenue = revenue;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner getReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner = (GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner) o;
    return Objects.equals(this.date, getReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner.date) &&
        Objects.equals(this.revenue, getReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner.revenue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, revenue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

