/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import io.github.erkoristhein.mailchimp.marketing.model.SignupForm;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * List Signup Forms.
 */
@JsonPropertyOrder({
  ListSignupForms.JSON_PROPERTY_SIGNUP_FORMS,
  ListSignupForms.JSON_PROPERTY_LIST_ID,
  ListSignupForms.JSON_PROPERTY_TOTAL_ITEMS,
  ListSignupForms.JSON_PROPERTY_LINKS
})
@JsonTypeName("List_Signup_Forms")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-23T16:28:01.262813+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class ListSignupForms {
  public static final String JSON_PROPERTY_SIGNUP_FORMS = "signup_forms";
  @jakarta.annotation.Nullable
  private List<SignupForm> signupForms = new ArrayList<>();

  public static final String JSON_PROPERTY_LIST_ID = "list_id";
  @jakarta.annotation.Nullable
  private String listId;

  public static final String JSON_PROPERTY_TOTAL_ITEMS = "total_items";
  @jakarta.annotation.Nullable
  private Integer totalItems;

  public static final String JSON_PROPERTY_LINKS = "_links";
  @jakarta.annotation.Nullable
  private List<ResourceLink> links = new ArrayList<>();

  public ListSignupForms() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ListSignupForms(
    @JsonProperty(JSON_PROPERTY_TOTAL_ITEMS) Integer totalItems, 
    @JsonProperty(JSON_PROPERTY_LINKS) List<ResourceLink> links
  ) {
    this();
    this.totalItems = totalItems;
    this.links = links;
  }

  public ListSignupForms signupForms(@jakarta.annotation.Nullable List<SignupForm> signupForms) {
    
    this.signupForms = signupForms;
    return this;
  }

  public ListSignupForms addSignupFormsItem(SignupForm signupFormsItem) {
    if (this.signupForms == null) {
      this.signupForms = new ArrayList<>();
    }
    this.signupForms.add(signupFormsItem);
    return this;
  }

  /**
   * List signup form.
   * @return signupForms
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SIGNUP_FORMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SignupForm> getSignupForms() {
    return signupForms;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNUP_FORMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignupForms(@jakarta.annotation.Nullable List<SignupForm> signupForms) {
    this.signupForms = signupForms;
  }

  public ListSignupForms listId(@jakarta.annotation.Nullable String listId) {
    
    this.listId = listId;
    return this;
  }

  /**
   * The list id.
   * @return listId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getListId() {
    return listId;
  }


  @JsonProperty(value = JSON_PROPERTY_LIST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListId(@jakarta.annotation.Nullable String listId) {
    this.listId = listId;
  }

  /**
   * The total number of items matching the query regardless of pagination.
   * @return totalItems
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalItems() {
    return totalItems;
  }



  /**
   * A list of link types and descriptions for the API schema documents.
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResourceLink> getLinks() {
    return links;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListSignupForms listSignupForms = (ListSignupForms) o;
    return Objects.equals(this.signupForms, listSignupForms.signupForms) &&
        Objects.equals(this.listId, listSignupForms.listId) &&
        Objects.equals(this.totalItems, listSignupForms.totalItems) &&
        Objects.equals(this.links, listSignupForms.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signupForms, listId, totalItems, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListSignupForms {\n");
    sb.append("    signupForms: ").append(toIndentedString(signupForms)).append("\n");
    sb.append("    listId: ").append(toIndentedString(listId)).append("\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

