/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The average campaign statistics for your list. This won&#39;t be present if we haven&#39;t calculated it yet for this list.
 */
@JsonPropertyOrder({
  ListStats.JSON_PROPERTY_SUB_RATE,
  ListStats.JSON_PROPERTY_UNSUB_RATE,
  ListStats.JSON_PROPERTY_OPEN_RATE,
  ListStats.JSON_PROPERTY_PROXY_EXCLUDED_OPEN_RATE,
  ListStats.JSON_PROPERTY_CLICK_RATE
})
@JsonTypeName("List_Stats")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-20T13:33:02.593663+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class ListStats {
  public static final String JSON_PROPERTY_SUB_RATE = "sub_rate";
  @jakarta.annotation.Nullable
  private BigDecimal subRate;

  public static final String JSON_PROPERTY_UNSUB_RATE = "unsub_rate";
  @jakarta.annotation.Nullable
  private BigDecimal unsubRate;

  public static final String JSON_PROPERTY_OPEN_RATE = "open_rate";
  @jakarta.annotation.Nullable
  private BigDecimal openRate;

  public static final String JSON_PROPERTY_PROXY_EXCLUDED_OPEN_RATE = "proxy_excluded_open_rate";
  @jakarta.annotation.Nullable
  private BigDecimal proxyExcludedOpenRate;

  public static final String JSON_PROPERTY_CLICK_RATE = "click_rate";
  @jakarta.annotation.Nullable
  private BigDecimal clickRate;

  public ListStats() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ListStats(
    @JsonProperty(JSON_PROPERTY_SUB_RATE) BigDecimal subRate, 
    @JsonProperty(JSON_PROPERTY_UNSUB_RATE) BigDecimal unsubRate, 
    @JsonProperty(JSON_PROPERTY_OPEN_RATE) BigDecimal openRate, 
    @JsonProperty(JSON_PROPERTY_PROXY_EXCLUDED_OPEN_RATE) BigDecimal proxyExcludedOpenRate, 
    @JsonProperty(JSON_PROPERTY_CLICK_RATE) BigDecimal clickRate
  ) {
    this();
    this.subRate = subRate;
    this.unsubRate = unsubRate;
    this.openRate = openRate;
    this.proxyExcludedOpenRate = proxyExcludedOpenRate;
    this.clickRate = clickRate;
  }

  /**
   * The average number of subscriptions per month for the list.
   * @return subRate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUB_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSubRate() {
    return subRate;
  }



  /**
   * The average number of unsubscriptions per month for the list.
   * @return unsubRate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNSUB_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getUnsubRate() {
    return unsubRate;
  }



  /**
   * The average unique open rate (a percentage represented as a number between 0 and 100) per campaign for the list.
   * @return openRate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getOpenRate() {
    return openRate;
  }



  /**
   * The average unique open rate (a percentage represented as a number between 0 and 100) per campaign for the list, excluding opens from email clients that use proxies.
   * @return proxyExcludedOpenRate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROXY_EXCLUDED_OPEN_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getProxyExcludedOpenRate() {
    return proxyExcludedOpenRate;
  }



  /**
   * The average click rate (a percentage represented as a number between 0 and 100) per campaign for the list.
   * @return clickRate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLICK_RATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getClickRate() {
    return clickRate;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListStats listStats = (ListStats) o;
    return Objects.equals(this.subRate, listStats.subRate) &&
        Objects.equals(this.unsubRate, listStats.unsubRate) &&
        Objects.equals(this.openRate, listStats.openRate) &&
        Objects.equals(this.proxyExcludedOpenRate, listStats.proxyExcludedOpenRate) &&
        Objects.equals(this.clickRate, listStats.clickRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subRate, unsubRate, openRate, proxyExcludedOpenRate, clickRate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListStats {\n");
    sb.append("    subRate: ").append(toIndentedString(subRate)).append("\n");
    sb.append("    unsubRate: ").append(toIndentedString(unsubRate)).append("\n");
    sb.append("    openRate: ").append(toIndentedString(openRate)).append("\n");
    sb.append("    proxyExcludedOpenRate: ").append(toIndentedString(proxyExcludedOpenRate)).append("\n");
    sb.append("    clickRate: ").append(toIndentedString(clickRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

