/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.81
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A single marketing permission a subscriber has either opted-in to or opted-out of.
 */
@JsonPropertyOrder({
  MarketingPermission.JSON_PROPERTY_MARKETING_PERMISSION_ID,
  MarketingPermission.JSON_PROPERTY_TEXT,
  MarketingPermission.JSON_PROPERTY_ENABLED
})
@JsonTypeName("Marketing_Permission")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-03T13:08:30.305646+02:00[Europe/Tallinn]")
public class MarketingPermission {
  public static final String JSON_PROPERTY_MARKETING_PERMISSION_ID = "marketing_permission_id";
  private String marketingPermissionId;

  public static final String JSON_PROPERTY_TEXT = "text";
  private String text;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  private Boolean enabled;

  public MarketingPermission() {
  }

  public MarketingPermission marketingPermissionId(String marketingPermissionId) {
    
    this.marketingPermissionId = marketingPermissionId;
    return this;
  }

   /**
   * The id for the marketing permission on the list
   * @return marketingPermissionId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKETING_PERMISSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMarketingPermissionId() {
    return marketingPermissionId;
  }


  @JsonProperty(JSON_PROPERTY_MARKETING_PERMISSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketingPermissionId(String marketingPermissionId) {
    this.marketingPermissionId = marketingPermissionId;
  }


  public MarketingPermission text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * The text of the marketing permission.
   * @return text
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(String text) {
    this.text = text;
  }


  public MarketingPermission enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * If the subscriber has opted-in to the marketing permission.
   * @return enabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketingPermission marketingPermission = (MarketingPermission) o;
    return Objects.equals(this.marketingPermissionId, marketingPermission.marketingPermissionId) &&
        Objects.equals(this.text, marketingPermission.text) &&
        Objects.equals(this.enabled, marketingPermission.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(marketingPermissionId, text, enabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketingPermission {\n");
    sb.append("    marketingPermissionId: ").append(toIndentedString(marketingPermissionId)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

