/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.SegmentOptions;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * List settings for the Automation.
 */
@JsonPropertyOrder({
  ModelList.JSON_PROPERTY_LIST_ID,
  ModelList.JSON_PROPERTY_LIST_IS_ACTIVE,
  ModelList.JSON_PROPERTY_LIST_NAME,
  ModelList.JSON_PROPERTY_SEGMENT_OPTS,
  ModelList.JSON_PROPERTY_STORE_ID
})
@JsonTypeName("List")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-26T16:39:59.516441+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class ModelList {
  public static final String JSON_PROPERTY_LIST_ID = "list_id";
  private String listId;

  public static final String JSON_PROPERTY_LIST_IS_ACTIVE = "list_is_active";
  private Boolean listIsActive;

  public static final String JSON_PROPERTY_LIST_NAME = "list_name";
  private String listName;

  public static final String JSON_PROPERTY_SEGMENT_OPTS = "segment_opts";
  private SegmentOptions segmentOpts;

  public static final String JSON_PROPERTY_STORE_ID = "store_id";
  private String storeId;

  public ModelList() {
  }

  @JsonCreator
  public ModelList(
    @JsonProperty(JSON_PROPERTY_LIST_IS_ACTIVE) Boolean listIsActive
  ) {
    this();
    this.listIsActive = listIsActive;
  }

  public ModelList listId(String listId) {
    
    this.listId = listId;
    return this;
  }

   /**
   * The unique list id.
   * @return listId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getListId() {
    return listId;
  }


  @JsonProperty(JSON_PROPERTY_LIST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListId(String listId) {
    this.listId = listId;
  }


   /**
   * The status of the list used, namely if it&#39;s deleted or disabled.
   * @return listIsActive
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIST_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getListIsActive() {
    return listIsActive;
  }




  public ModelList listName(String listName) {
    
    this.listName = listName;
    return this;
  }

   /**
   * List Name.
   * @return listName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getListName() {
    return listName;
  }


  @JsonProperty(JSON_PROPERTY_LIST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListName(String listName) {
    this.listName = listName;
  }


  public ModelList segmentOpts(SegmentOptions segmentOpts) {
    
    this.segmentOpts = segmentOpts;
    return this;
  }

   /**
   * Get segmentOpts
   * @return segmentOpts
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEGMENT_OPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SegmentOptions getSegmentOpts() {
    return segmentOpts;
  }


  @JsonProperty(JSON_PROPERTY_SEGMENT_OPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSegmentOpts(SegmentOptions segmentOpts) {
    this.segmentOpts = segmentOpts;
  }


  public ModelList storeId(String storeId) {
    
    this.storeId = storeId;
    return this;
  }

   /**
   * The id of the store.
   * @return storeId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STORE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStoreId() {
    return storeId;
  }


  @JsonProperty(JSON_PROPERTY_STORE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelList _list = (ModelList) o;
    return Objects.equals(this.listId, _list.listId) &&
        Objects.equals(this.listIsActive, _list.listIsActive) &&
        Objects.equals(this.listName, _list.listName) &&
        Objects.equals(this.segmentOpts, _list.segmentOpts) &&
        Objects.equals(this.storeId, _list.storeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listId, listIsActive, listName, segmentOpts, storeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelList {\n");
    sb.append("    listId: ").append(toIndentedString(listId)).append("\n");
    sb.append("    listIsActive: ").append(toIndentedString(listIsActive)).append("\n");
    sb.append("    listName: ").append(toIndentedString(listName)).append("\n");
    sb.append("    segmentOpts: ").append(toIndentedString(segmentOpts)).append("\n");
    sb.append("    storeId: ").append(toIndentedString(storeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

