/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ListMembers2;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Partial matches of the provided search query.
 */
@JsonPropertyOrder({
  PartialMatches.JSON_PROPERTY_MEMBERS,
  PartialMatches.JSON_PROPERTY_TOTAL_ITEMS
})
@JsonTypeName("Partial_Matches")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-20T12:52:34.947879+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class PartialMatches {
  public static final String JSON_PROPERTY_MEMBERS = "members";
  @jakarta.annotation.Nullable
  private List<ListMembers2> members = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL_ITEMS = "total_items";
  @jakarta.annotation.Nullable
  private Integer totalItems;

  public PartialMatches() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public PartialMatches(
    @JsonProperty(JSON_PROPERTY_TOTAL_ITEMS) Integer totalItems
  ) {
    this();
    this.totalItems = totalItems;
  }

  public PartialMatches members(@jakarta.annotation.Nullable List<ListMembers2> members) {
    
    this.members = members;
    return this;
  }

  public PartialMatches addMembersItem(ListMembers2 membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

  /**
   * An array of objects, each representing a specific list member.
   * @return members
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ListMembers2> getMembers() {
    return members;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMembers(@jakarta.annotation.Nullable List<ListMembers2> members) {
    this.members = members;
  }

  /**
   * The total number of items matching the query regardless of pagination.
   * @return totalItems
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalItems() {
    return totalItems;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartialMatches partialMatches = (PartialMatches) o;
    return Objects.equals(this.members, partialMatches.members) &&
        Objects.equals(this.totalItems, partialMatches.totalItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(members, totalItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartialMatches {\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

