/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.81
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Deprecated
 */
@JsonPropertyOrder({
  SalesforceCRMTracking.JSON_PROPERTY_CAMPAIGN,
  SalesforceCRMTracking.JSON_PROPERTY_NOTES
})
@JsonTypeName("Salesforce_CRM_Tracking")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-03T13:08:30.305646+02:00[Europe/Tallinn]")
public class SalesforceCRMTracking {
  public static final String JSON_PROPERTY_CAMPAIGN = "campaign";
  private Boolean campaign;

  public static final String JSON_PROPERTY_NOTES = "notes";
  private Boolean notes;

  public SalesforceCRMTracking() {
  }

  public SalesforceCRMTracking campaign(Boolean campaign) {
    
    this.campaign = campaign;
    return this;
  }

   /**
   * Create a campaign in a connected Salesforce account.
   * @return campaign
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAMPAIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCampaign() {
    return campaign;
  }


  @JsonProperty(JSON_PROPERTY_CAMPAIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaign(Boolean campaign) {
    this.campaign = campaign;
  }


  public SalesforceCRMTracking notes(Boolean notes) {
    
    this.notes = notes;
    return this;
  }

   /**
   * Update contact notes for a campaign based on a subscriber&#39;s email address.
   * @return notes
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNotes() {
    return notes;
  }


  @JsonProperty(JSON_PROPERTY_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotes(Boolean notes) {
    this.notes = notes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesforceCRMTracking salesforceCRMTracking = (SalesforceCRMTracking) o;
    return Objects.equals(this.campaign, salesforceCRMTracking.campaign) &&
        Objects.equals(this.notes, salesforceCRMTracking.notes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaign, notes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesforceCRMTracking {\n");
    sb.append("    campaign: ").append(toIndentedString(campaign)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

