/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ListMembers1;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * View members in a specific list segment.
 */
@JsonPropertyOrder({
  SegmentMembers.JSON_PROPERTY_MEMBERS,
  SegmentMembers.JSON_PROPERTY_TOTAL_ITEMS,
  SegmentMembers.JSON_PROPERTY_LINKS
})
@JsonTypeName("Segment_Members")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-23T16:28:01.262813+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class SegmentMembers {
  public static final String JSON_PROPERTY_MEMBERS = "members";
  @jakarta.annotation.Nullable
  private List<ListMembers1> members = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL_ITEMS = "total_items";
  @jakarta.annotation.Nullable
  private Integer totalItems;

  public static final String JSON_PROPERTY_LINKS = "_links";
  @jakarta.annotation.Nullable
  private List<ResourceLink> links = new ArrayList<>();

  public SegmentMembers() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public SegmentMembers(
    @JsonProperty(JSON_PROPERTY_TOTAL_ITEMS) Integer totalItems, 
    @JsonProperty(JSON_PROPERTY_LINKS) List<ResourceLink> links
  ) {
    this();
    this.totalItems = totalItems;
    this.links = links;
  }

  public SegmentMembers members(@jakarta.annotation.Nullable List<ListMembers1> members) {
    
    this.members = members;
    return this;
  }

  public SegmentMembers addMembersItem(ListMembers1 membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

  /**
   * An array of objects, each representing a specific list member.
   * @return members
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ListMembers1> getMembers() {
    return members;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMembers(@jakarta.annotation.Nullable List<ListMembers1> members) {
    this.members = members;
  }

  /**
   * The total number of items matching the query regardless of pagination.
   * @return totalItems
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalItems() {
    return totalItems;
  }



  /**
   * A list of link types and descriptions for the API schema documents.
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResourceLink> getLinks() {
    return links;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SegmentMembers segmentMembers = (SegmentMembers) o;
    return Objects.equals(this.members, segmentMembers.members) &&
        Objects.equals(this.totalItems, segmentMembers.totalItems) &&
        Objects.equals(this.links, segmentMembers.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(members, totalItems, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SegmentMembers {\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

