/*
 * Mailchimp Marketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.90
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.erkoristhein.mailchimp.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.erkoristhein.mailchimp.marketing.model.ResourceLink;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A list of members who have unsubscribed from a specific campaign.
 */
@JsonPropertyOrder({
  Unsubscribes.JSON_PROPERTY_UNSUBSCRIBES,
  Unsubscribes.JSON_PROPERTY_CAMPAIGN_ID,
  Unsubscribes.JSON_PROPERTY_TOTAL_ITEMS,
  Unsubscribes.JSON_PROPERTY_LINKS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-23T15:30:38.569460+02:00[Europe/Tallinn]", comments = "Generator version: 7.17.0")
public class Unsubscribes {
  public static final String JSON_PROPERTY_UNSUBSCRIBES = "unsubscribes";
  @jakarta.annotation.Nullable
  private List<Unsubscribes> unsubscribes = new ArrayList<>();

  public static final String JSON_PROPERTY_CAMPAIGN_ID = "campaign_id";
  @jakarta.annotation.Nullable
  private String campaignId;

  public static final String JSON_PROPERTY_TOTAL_ITEMS = "total_items";
  @jakarta.annotation.Nullable
  private Integer totalItems;

  public static final String JSON_PROPERTY_LINKS = "_links";
  @jakarta.annotation.Nullable
  private List<ResourceLink> links = new ArrayList<>();

  public Unsubscribes() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public Unsubscribes(
    @JsonProperty(JSON_PROPERTY_CAMPAIGN_ID) String campaignId, 
    @JsonProperty(JSON_PROPERTY_TOTAL_ITEMS) Integer totalItems, 
    @JsonProperty(JSON_PROPERTY_LINKS) List<ResourceLink> links
  ) {
    this();
    this.campaignId = campaignId;
    this.totalItems = totalItems;
    this.links = links;
  }

  public Unsubscribes unsubscribes(@jakarta.annotation.Nullable List<Unsubscribes> unsubscribes) {
    
    this.unsubscribes = unsubscribes;
    return this;
  }

  public Unsubscribes addUnsubscribesItem(Unsubscribes unsubscribesItem) {
    if (this.unsubscribes == null) {
      this.unsubscribes = new ArrayList<>();
    }
    this.unsubscribes.add(unsubscribesItem);
    return this;
  }

  /**
   * An array of objects, each representing a member who unsubscribed from a campaign.
   * @return unsubscribes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Unsubscribes> getUnsubscribes() {
    return unsubscribes;
  }


  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnsubscribes(@jakarta.annotation.Nullable List<Unsubscribes> unsubscribes) {
    this.unsubscribes = unsubscribes;
  }

  /**
   * The campaign id.
   * @return campaignId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCampaignId() {
    return campaignId;
  }



  /**
   * The total number of items matching the query regardless of pagination.
   * @return totalItems
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalItems() {
    return totalItems;
  }



  /**
   * A list of link types and descriptions for the API schema documents.
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResourceLink> getLinks() {
    return links;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Unsubscribes unsubscribes = (Unsubscribes) o;
    return Objects.equals(this.unsubscribes, unsubscribes.unsubscribes) &&
        Objects.equals(this.campaignId, unsubscribes.campaignId) &&
        Objects.equals(this.totalItems, unsubscribes.totalItems) &&
        Objects.equals(this.links, unsubscribes.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unsubscribes, campaignId, totalItems, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Unsubscribes {\n");
    sb.append("    unsubscribes: ").append(toIndentedString(unsubscribes)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

